Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/AttiTrattazioneController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using PortaleRegione.Client.Helpers;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Model;
using PortaleRegione.Gateway;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller atti dasi trattazione
    /// </summary>
    [Authorize]
    [RoutePrefix("attitrattazione")]
    public class AttiTrattazioneController : BaseController
    {
        [HttpGet]
        [Route("view")]
        public async Task<ActionResult> Index(Guid id)
        {
            CheckCacheClientMode(ClientModeEnum.TRATTAZIONE);
            var mode = (ClientModeEnum)HttpContext.Cache.Get(GetCacheKey(CacheHelper.CLIENT_MODE));
            var apiGateway = new ApiGateway(Token);
            var seduta = await apiGateway.Sedute.Get(id);
            var model = new DashboardModel
            {
                Seduta = seduta,
                CurrentUser = CurrentUser
            };
            var attiPEM = await apiGateway.Atti.Get(id, mode, 1, 99);
            if (attiPEM.Results.Any())
                model.PEM.Add(attiPEM);

            var attiDASI = await apiGateway.DASI.GetBySeduta(id);
            if (attiDASI == null)
                attiDASI = new RiepilogoDASIModel();
            model.DASI.Add(attiDASI);

            return View("Index", model);
        }

        public async Task<ActionResult> Archivio(int page = 1, int size = 20)
        {
            CheckCacheClientMode(ClientModeEnum.TRATTAZIONE);

            var apiGateway = new ApiGateway(Token);
            var model = await apiGateway.Sedute.Get(page, size);
            return View("Archivio", model);
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/DASIController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Mvc;
using ExpressionBuilder.Common;
using ExpressionBuilder.Generics;
using Newtonsoft.Json;
using PortaleRegione.Client.Helpers;
using PortaleRegione.DTO.Domain;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Model;
using PortaleRegione.DTO.Request;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;
using Utility = PortaleRegione.Common.Utility;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller per la gestione degli Atti di Sindacato Ispettivo
    /// </summary>
    [Authorize]
    [RoutePrefix("dasi")]
    public class DASIController : BaseController
    {
        /// <summary>
        ///     Endpoint per visualizzare il riepilogo degli Atti di Sindacato ispettivo in base al ruolo dell'utente loggato
        /// </summary>
        /// <returns></returns>
        [Route("riepilogo")]
        public async Task<ActionResult> RiepilogoDASI(int page = 1, int size = 20, int view = (int)ViewModeEnum.GRID,
            int stato = (int)StatiAttoEnum.BOZZA, int tipo = (int)TipoAttoEnum.TUTTI)
        {
            var currentUser = CurrentUser;
            if (CanAccess(new List<RuoliIntEnum>
                    { RuoliIntEnum.Amministratore_PEM
                        , RuoliIntEnum.Segreteria_Assemblea
                        , RuoliIntEnum.Segreteria_Assemblea_Read }))
            {
                return View("RiepilogoDASI_Admin", new RiepilogoDASIModel
                {
                    CurrentUser = currentUser
                });
            }

            CheckCacheClientMode(ClientModeEnum.GRUPPI);
            await CheckCacheGruppiAdmin(currentUser.CurrentRole);
            var view_require_my_sign = Convert.ToBoolean(Request.QueryString["require_my_sign"]);

            var apiGateway = new ApiGateway(Token);
            var currentLegislatura = await apiGateway.Legislature.GetLegislaturaAttuale();
            var model = await apiGateway.DASI.Get(page, size, (StatiAttoEnum)stato, (TipoAttoEnum)tipo,
                currentUser.CurrentRole, currentLegislatura, view_require_my_sign);
            model.CurrentUser = currentUser;
            SetCache(page, size, tipo, stato, view);
            if (view == (int)ViewModeEnum.PREVIEW)
            {
                model.ViewMode = ViewModeEnum.PREVIEW;
                foreach (var atti in model.Data.Results)
                    atti.BodyAtto =
                        await apiGateway.DASI.GetBody(atti.UIDAtto, TemplateTypeEnum.HTML);
            }

            Session["RiepilogoDASI"] = model;
            return View("RiepilogoDASI", model);
        }

        [HttpPost]
        [Route("riepilogoUOLA")]
        public async Task<ActionResult> Riepilogo(FilterRequest model)
        {
            try
            {
                var request = new BaseRequest<AttoDASIDto>
                {
                    page = 1,
                    size = 20,
                    param = new Dictionary<string, object>
                    {
                        { "CLIENT_MODE", model.clientMode },
                        { nameof(FilterRequest.viewMode), model.viewMode }
                    }
                };

                if (!model.filters.Any())
                {
                    var resEmpty = new RiepilogoDASIModel
                    {
                        CurrentUser = CurrentUser
                    };
                    return Json(resEmpty);
                }

                // #990
                if (model.sort_settings.Any())
                {
                    request.dettagliOrdinamento = model.sort_settings;
                }
                
                // #1191
                if (model.columns_settings.Any())
                {
                    request.columns = model.columns_settings;
                }

                request.page = model.page;
                request.size = model.size;

                var apiGateway = new ApiGateway(Token);
                request.filtro.AddRange(Utility.ParseFilterDasi(model.filters));

                var res = await apiGateway.DASI.Get(request);
                res.CurrentUser = CurrentUser;

                return Json(res);
            }
            catch (Exception e)
            {
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Route("riepilogoSoloIds")]
        public async Task<ActionResult> RiepilogoSoloIds(FilterRequest model)
        {
            try
            {
                var request = new BaseRequest<AttoDASIDto>
                {
                    page = 1,
                    size = 20,
                    param = new Dictionary<string, object>
                    {
                        { "CLIENT_MODE", model.clientMode },
                        { nameof(FilterRequest.viewMode), model.viewMode }
                    }
                };

                if (!model.filters.Any())
                {
                    var resEmpty = new RiepilogoDASIModel
                    {
                        CurrentUser = CurrentUser
                    };
                    return Json(resEmpty);
                }

                // #990
                if (model.sort_settings.Any())
                {
                    request.dettagliOrdinamento = model.sort_settings;
                }
                
                // #1191
                if (model.columns_settings.Any())
                {
                    request.columns = model.columns_settings;
                }

                request.page = model.page;
                request.size = model.size;

                var apiGateway = new ApiGateway(Token);
                request.filtro.AddRange(Utility.ParseFilterDasi(model.filters));

                var res = await apiGateway.DASI.GetSoloIds(request);
                return Json(res);
            }
            catch (Exception e)
            {
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Route("salva-gruppo-filtri")]
        public async Task<ActionResult> SalvaGruppoFiltri(FiltroPreferitoDto model)
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                await apiGateway.DASI.SalvaGruppoFiltri(model);
                return Json("OK");
            }
            catch (Exception e)
            {
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [Route("elimina-gruppo-filtri")]
        public async Task<ActionResult> EliminaGruppoFiltri(string nomeFiltro)
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                await apiGateway.DASI.EliminaGruppoFiltri(nomeFiltro);
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [Route("gruppo-filtri")]
        public async Task<ActionResult> GetGruppoFiltri()
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                var res = await apiGateway.DASI.GetGruppoFiltri();
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        ///     Endpoint per visualizzare il riepilogo degli Atti di Sindacato ispettivo in base al ruolo dell'utente loggato
        /// </summary>
        /// <returns></returns>
        public Task<ActionResult> RiepilogoDASI()
        {
            var model = new RiepilogoDASIModel
            {
                CurrentUser = CurrentUser
            };

            if (CanAccess(new List<RuoliIntEnum>
                    { RuoliIntEnum.Amministratore_PEM
                        , RuoliIntEnum.Segreteria_Assemblea
                        , RuoliIntEnum.Segreteria_Assemblea_Read }))
                return Task.FromResult<ActionResult>(View("RiepilogoDASI_Admin", model));

            return Task.FromResult<ActionResult>(View("RiepilogoDASI", model));
        }

        /// <summary>
        ///     Endpoint per visualizzare il riepilogo degli Atti di Sindacato ispettivo cartacei
        /// </summary>
        /// <returns></returns>
        [Route("cartacei")]
        public async Task<ActionResult> RiepilogoCartacei()
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                return Json(await apiGateway.DASI.GetCartacei(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/AttiTrattazione/Archivio.cshtml
@using PortaleRegione.Common
@model PortaleRegione.DTO.Response.BaseResponse<PortaleRegione.DTO.Domain.SeduteDto>

@{
    ViewBag.Title = "Sedute";
    if (Model.Filters.Any())
    {
        ViewBag.Title += " - Ricerca";
    }
}

<div class="row">
    <div class="col s12">
        <h4>
            <b>@ViewBag.Title</b>
        </h4>
    </div>
</div>

@{
    Html.RenderPartial("_PaginationBar", Model.Paging);
}

<div id="seduteTable" class="row">

    @if (!Model.Results.Any())
    {
        <div class="row">
            <div class="col s12">
                <div class="card-panel panel-warning center">
                    <span class="center">
                        Non ci sono sedute al momento
                    </span>
                </div>
            </div>
        </div>
    }

    <ul id="gridView" class="collapsible expandable">
        @foreach (var seduta in Model.Results)
        {
            var css_sedutaAttiva = "green lighten-4 black-text";
            if (seduta.Data_effettiva_fine.HasValue)
            {
                if (seduta.Data_effettiva_fine.Value < DateTime.Now)
                {
                    css_sedutaAttiva = string.Empty;
                }
            }
            
            var colorStato = "badgeSedutaArchiviata";

            if (!seduta.Data_apertura.HasValue)
            {
                colorStato = "badgeSedutaChiusa";
            }
            else if (seduta.Data_apertura > DateTime.Now)
            {
                colorStato = "badgeSedutaChiusa";
            }
            else if (!string.IsNullOrEmpty(css_sedutaAttiva))
            {
                colorStato = "badgeSedutaAperta";
            }

            <li class="badgeBody @colorStato">
                <div class="collapsible-header" tabindex="0">
                    <div class="col s8 valign-wrapper">
                        <span style="padding-right: 50px">Seduta del @seduta.Data_seduta.ToString("dd/MM/yyyy HH:mm")</span>
                        @if (!seduta.Data_apertura.HasValue)
                        {
                        }
                        else if (seduta.Data_apertura > DateTime.Now)
                        {
                        }
                        else if (!string.IsNullOrEmpty(css_sedutaAttiva))
                        {
                            <div class="btn-flat green-text hide-on-med-and-down">Aperta</div>
                        }
                        @if (!string.IsNullOrEmpty(seduta.Note))
                        {
                            <div class="btn-flat purple-text hide-on-med-and-down">@seduta.Note</div>
                        }
                    </div>

                    @*COMANDI*@
                    <div class="col s4 right-align" style="margin-top: 15px;">
                        <button type="button" role="button" class="btn-flat black-text tooltipped" onclick="go('@Url.Action("Index", "AttiTrattazione", new { id = seduta.UIDSeduta })')" data-tooltip="Riepilogo atti in seduta">
                            RIEPILOGO SEDUTA
                        </button>
                    </div>
                </div>
                <div class="collapsible-body">
                    <div class="row">
                        <div class="col s12">
                            <ul class="collection">
                                @foreach (var atto in seduta.AttiList)
                                {
                                    <li class="collection-item">
                                        <label><b>@Utility.GetText_Tipo(atto.IDTipoAtto) @atto.NAtto </b> - @atto.Oggetto</label>
                                    </li>
                                }
                                @foreach (var dasiTipoId in seduta.DasiList)
                                {
                                    <li class="collection-item" style="font-weight: normal!important;">
                                        <label>@Utility.GetText_Tipo(dasiTipoId)</label>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
</div>

@{
    Html.RenderPartial("_SeduteFiltri", Model.Paging);
}

<script>
    $(document).ready(function() {
        var filters = @Html.Raw(Convert.ToInt16(Model.Filters.Any()));
        if (filters == 0)
            set_Filtri_Sedute({});

        Filtri_Sedute_CaricaLegislature("filter_sedute_legislature");
        Filtri_Sedute_CaricaAnni("filter_sedute_anno");
        Filtri_Sedute_CaricaDa("filter_sedute_da");
        Filtri_Sedute_CaricaA("filter_sedute_a");

        $('#btnSearch').on("click",
            function() {
                openSearch();
            });
    });

    function filtra() {
        setTimeout(function() {
                $('body').removeClass('loaded');
            },
            200);
        $('#formFiltraSedute').submit();
    }

    function filtra(page) {
        $('#inputFilterPage').val(page);
        setTimeout(function() {
                $('body').removeClass('loaded');
            },
            200);
        $('#formFiltraSedute').submit();
    }
</script>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/AttiTrattazione/Index.cshtml
@using PortaleRegione.Client.Helpers
@using PortaleRegione.DTO.Enum
@using Utility = PortaleRegione.Common.Utility
@model PortaleRegione.DTO.Model.DashboardModel

@{
    ViewBag.Title = $"Seduta del {Model.Seduta.Data_seduta.ToString("dd/MM/yyyy HH:mm")}";
    var DASIEnabled = Model.CurrentUser.CurrentRole != RuoliIntEnum.Utente
                      && !Model.CurrentUser.IsGiunta
                      && AppSettingsConfiguration.EnableDASI;
    var PEMEnabled = Model.CurrentUser.CurrentRole != RuoliIntEnum.Utente
                     && AppSettingsConfiguration.EnablePEM;

    var seduta = Model.Seduta;
}

<div class="row">
    <div class="col s12">
        <a class="btn-floating waves-effect waves-light grey darken-3" href="@Url.Action("Archivio")">
            <i class="material-icons">arrow_back</i>
        </a>
    </div>
</div>
<div class="row valign-wrapper" style="margin-bottom: 0px !important">
    <div class="col s12">
        <h4>
            <b>@ViewBag.Title</b>
        </h4>
    </div>
</div>

@if (Model.PEM.Any() && PEMEnabled)
{
    <div class="row" style="margin: 0 !important">
        <div class="col s12">
            <h5>
                <b>Atti iscritti alla seduta</b>
            </h5>
        </div>
    </div>
    <hr/>

    <ul class="collapsible" style="position: relative">
        @foreach (var attoPem in Model.PEM.First().Results)
        {
            var titolo_atto = $"{Utility.GetText_Tipo(attoPem.IDTipoAtto)} {attoPem.NAtto}";
            if (attoPem.IDTipoAtto == (int)TipoAttoEnum.ALTRO)
            {
                titolo_atto = attoPem.Oggetto;
            }
            <li>
                <div class="collapsible-header">
                    <i class="material-icons pink-text hide-on-med-and-down">textsms</i>
                    @titolo_atto
                    <div class="collapsabile-secondary-header">
                        @if (attoPem.Emendabile)
                        {
                            <div class="chip">@(attoPem.Conteggio_EM + attoPem.Conteggio_SubEM) EM</div>
                        }
                        @if (attoPem.CounterODG > 0)
                        {
                            <div class="chip">@(attoPem.CounterODG) ODG</div>
                        }
                    </div>
                </div>
                <div class="collapsible-body">
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col l12 s12">
                                    <div class="card-panel grey lighten-5">
                                        <label>
                                            <b>Oggetto</b>
                                        </label>
                                        <br/>
                                        <p>@attoPem.Oggetto</p>

                                        @if (!string.IsNullOrEmpty(attoPem.Path_Testo_Atto))
                                        {
                                            <div class="row">
                                                <div class="col s12 l12 right-align">
                                                    <button type="button" role="button" class="btn-flat pink-text"
                                                       href="@Url.Action("Download", "Atti", new { path = attoPem.Path_Testo_Atto })">
                                                        Scarica atto
                                                    </button>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                @if (attoPem.UIDAssessoreRiferimento.HasValue)
                                {
                                    <div class="col s12">
                                        <label>
                                            <b>Assessore di Riferimento</b>
                                        </label>
                                        <br/>
                                        <div class="chip" style="margin-left: 5px; min-width: unset;">
                                            <img src="https://pubblicazioniweb.consiglio.regione.lombardia.it/fotocons/@attoPem.PersonaAssessore.foto" alt="@attoPem.PersonaAssessore.DisplayName">
                                            @attoPem.PersonaAssessore.DisplayName
                                        </div>
                                    </div>
                                }
                                @if (attoPem.Relatori.Any())
                                {
                                    <div class="col s12">
                                        <label>
                                            <b>Relatori</b>
                                        </label>
                                        <br/>
                                        @Html.Raw(PortaleRegione.Client.Helpers.Utility.GetRelatori(attoPem.Relatori))
                                    </div>
                                }

                            </div>
                            <div class="col l6 s12 right-align">
                                @if (!string.IsNullOrEmpty(attoPem.LinkFascicoloPresentazione))
                                {
                                    <a class="btn-flat orange-text"
                                       href="@attoPem.LinkFascicoloPresentazione"
                                       target="_blank">
                                        Scarica fascicolo presentazione
                                    </a>
                                }

                                @if (!string.IsNullOrEmpty(attoPem.LinkFascicoloVotazione))
                                {
                                    <a class="btn-flat orange-text"
                                       href="@attoPem.LinkFascicoloVotazione"
                                       target="_blank">
                                        Scarica fascicolo votazione
                                    </a>
                                }

                                @if (attoPem.Data_apertura.HasValue && attoPem.Emendabile)
                                {
                                    <button class="btn-flat blue-text tooltipped"
                                            onclick="go('@Url.Action("RiepilogoEmendamenti", "Emendamenti", new { id = attoPem.UIDAtto })')" data-tooltip="Riepilogo emendamenti/subemendamenti">
                                        Riepilogo EM/SUBEM
                                    </button>
                                }

                                @if (attoPem.CounterODG > 0)
                                {
                                    <button class="btn-flat blue-text tooltipped"
                                            onclick="go('@Url.Action("RiepilogoDASI_BySeduta", "DASI", new { id = attoPem.UIDSeduta, tipo = (int)TipoAttoEnum.ODG, uidAtto = attoPem.UIDAtto, legislatura = attoPem.Legislatura })')" data-tooltip="Riepilogo ordini del giorno">
                                        Riepilogo ODG
                                    </button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
}

@if (Model.DASI.Any() && DASIEnabled)
{
    var attoDasi = Model.DASI.First();
    if (attoDasi.Data.Results.Any())
    {
        var sedutaUid = attoDasi.Data.Results.First().UIDSeduta;
        var legislaturaId = attoDasi.Data.Results.First().Legislatura;
        <div class="row" style="margin: 0 !important">
            <div class="col s12">
                <h6>
                    <b>Atti di indirizzo e sindacato ispettivo</b>
                </h6>
            </div>
        </div>
        <hr/>
        <ul class="collapsible" style="position: relative">

            @if (attoDasi.CountBarData.ITL > 0)
            {
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons pink-text">textsms</i>
                        @Utility.GetText_Tipo((int)TipoAttoEnum.ITL)
                        <div class="collapsabile-secondary-header">
                            <div class="chip">@(attoDasi.CountBarData.ITL) Atti</div>
                        </div>
                    </div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col s12 right-align">
                                <button type="button" role="button" class="btn-flat blue-text"
                                   onclick="go('@Url.Action("RiepilogoDASI_BySeduta", "DASI", new { id = sedutaUid, tipo = (int)TipoAttoEnum.ITL, legislatura = legislaturaId })')" title="Riepilogo atti in seduta">
                                    Riepilogo Atti In Seduta
                                </button>
                            </div>
                        </div>
                    </div>
                </li>
            }
            @if (attoDasi.CountBarData.IQT > 0)
            {
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons pink-text">textsms</i>
                        @Utility.GetText_Tipo((int)TipoAttoEnum.IQT)
                        <div class="collapsabile-secondary-header">
                            <div class="chip">@(attoDasi.CountBarData.IQT) Atti</div>
                        </div>
                    </div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col s12 right-align">
                                <button type="button" role="button" class="btn-flat blue-text"
                                   onclick="go('@Url.Action("RiepilogoDASI_BySeduta", "DASI", new { id = sedutaUid, tipo = (int)TipoAttoEnum.IQT, legislatura = legislaturaId })')" title="Riepilogo atti in seduta">
                                    Riepilogo Atti In Seduta
                                </button>
                            </div>
                        </div>
                    </div>
                </li>
            }
            @if (attoDasi.CountBarData.MOZ > 0)
            {
                <li>
                    <div class="collapsible-header">
                        <i class="material-icons pink-text">textsms</i>
                        @Utility.GetText_Tipo((int)TipoAttoEnum.MOZ)
                        <div class="collapsabile-secondary-header">
                            <div class="chip">@(attoDasi.CountBarData.MOZ) Atti</div>
                        </div>
                    </div>
                    <div class="collapsible-body">
                        <div class="row">
                            <div class="col s12 right-align">
                                <button type="button" role="button" class="btn-flat blue-text"
                                   onclick="go('@Url.Action("RiepilogoDASI_BySeduta", "DASI", new { id = sedutaUid, tipo = (int)TipoAttoEnum.MOZ, legislatura = legislaturaId })')" title="Riepilogo atti in seduta">
                                    Riepilogo Atti In Seduta
                                </button>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
    }
}

<div class="row" style="margin: 0 !important">
    <div class="col s12">
        <h5>
            <b>Scadenze</b>
        </h5>
    </div>
</div>
<ul class="collection">
    @if (seduta.Scadenza_presentazione.HasValue)
    {
        <li class="collection-item">
            <b>EMENDAMENTI</b> @Convert.ToDateTime(seduta.Scadenza_presentazione).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
    @if (seduta.DataScadenzaPresentazioneIQT.HasValue)
    {
        <li class="collection-item">
            <b>INTERROGAZIONE A RISPOSTA IMMEDIATA</b> @Convert.ToDateTime(seduta.DataScadenzaPresentazioneIQT).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
    @if (seduta.DataScadenzaPresentazioneMOZ.HasValue)
    {
        <li class="collection-item">
            <b>MOZIONI</b> @Convert.ToDateTime(seduta.DataScadenzaPresentazioneMOZ).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
    @if (seduta.DataScadenzaPresentazioneMOZU.HasValue)
    {
        <li class="collection-item">
            <b>MOZIONI URGENTI</b> @Convert.ToDateTime(seduta.DataScadenzaPresentazioneMOZU).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
    @if (seduta.DataScadenzaPresentazioneMOZA.HasValue)
    {
        <li class="collection-item">
            <b>MOZIONI ABBINATE</b> @Convert.ToDateTime(seduta.DataScadenzaPresentazioneMOZA).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
    @if (seduta.DataScadenzaPresentazioneODG.HasValue)
    {
        <li class="collection-item">
            <b>ORDINI DEL GIORNO</b> @Convert.ToDateTime(seduta.DataScadenzaPresentazioneODG).ToString("dd/MM/yyyy HH:mm")
        </li>
    }
</ul>

<script>
    $(document).ready(function() {
        $('#btnSearch').hide();
        
        localStorage.setItem("filtriDasi", JSON.stringify([]));
    });
</script>