Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/AdminPanelController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using ExpressionBuilder.Common;
using ExpressionBuilder.Generics;
using PortaleRegione.Client.Models;
using PortaleRegione.DTO.Domain;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Model;
using PortaleRegione.DTO.Request;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller amministrazione
    /// </summary>
    [RoutePrefix("adminpanel")]
    public class AdminPanelController : BaseController
    {
        /// <summary>
        ///     Controller per visualizzare i dati degli utenti
        /// </summary>
        /// <param name="page">Pagina corrente</param>
        /// <param name="size">Paginazione</param>
        /// <returns></returns>
        [HttpGet]
        [Route("users/view")]
        public async Task<ActionResult> RiepilogoUtenti(int page = 1, int size = 20)
        {
            var request = new BaseRequest<PersonaDto> { page = page, size = size };
            var apiGateway = new ApiGateway(Token);
            return View("RiepilogoUtenti", await apiGateway.Admin.GetPersone(request));
        }

        /// <summary>
        ///     Controller per ricercare gli utenti
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("users/view")]
        public async Task<ActionResult> SearchUsers()
        {
            int.TryParse(Request.Form["page"], out var filtro_page);
            int.TryParse(Request.Form["size"], out var filtro_size);
            var filtro_q = Request.Form["q"];
            var filtro_no_cons = Request.Form["no_cons"];
            var filtro_legislatura = Request.Form["legislatura"];
            var filtro_ruoli = Request.Form["ruoli"];
            var filtro_gruppi = Request.Form["gruppi"];
            var request = new BaseRequest<PersonaDto> { page = filtro_page, size = filtro_size };
            if (!string.IsNullOrEmpty(filtro_q))
            {
                request.filtro.Add(new FilterStatement<PersonaDto>
                {
                    PropertyId = nameof(PersonaDto.nome),
                    Operation = Operation.Contains,
                    Value = filtro_q,
                    Connector = FilterStatementConnector.Or
                });
                request.filtro.Add(new FilterStatement<PersonaDto>
                {
                    PropertyId = nameof(PersonaDto.cognome),
                    Operation = Operation.Contains,
                    Value = filtro_q,
                    Connector = FilterStatementConnector.And
                });
            }

            if (filtro_no_cons == "on")
            {
                request.filtro.Add(new FilterStatement<PersonaDto>
                {
                    PropertyId = nameof(PersonaDto.No_Cons),
                    Operation = Operation.EqualTo,
                    Value = 1,
                    Connector = FilterStatementConnector.And
                });
            }

            if (!string.IsNullOrEmpty(filtro_legislatura))
            {
                var split_filter = filtro_legislatura.Split(',');
                foreach (var s in split_filter)
                {
                    request.filtro.Add(new FilterStatement<PersonaDto>
                    {
                        PropertyId = nameof(PersonaDto.legislature),
                        Operation = Operation.Contains,
                        Value = $"-{s}-",
                        Connector = FilterStatementConnector.And
                    });
                }
            }

            if (!string.IsNullOrEmpty(filtro_ruoli))
            {
                var split_filter = filtro_ruoli.Split(',');
                foreach (var s in split_filter)
                {
                    request.filtro.Add(new FilterStatement<PersonaDto>
                    {
                        PropertyId = nameof(PersonaDto.Ruoli),
                        Operation = Operation.EqualTo,
                        Value = s,
                        Connector = FilterStatementConnector.And
                    });
                }
            }

            if (!string.IsNullOrEmpty(filtro_gruppi))
            {
                var split_filter = filtro_gruppi.Split(',');
                foreach (var s in split_filter)
                {
                    request.filtro.Add(new FilterStatement<PersonaDto>
                    {
                        PropertyId = nameof(PersonaDto.id_gruppo_politico_rif),
                        Operation = Operation.EqualTo,
                        Value = s,
                        Connector = FilterStatementConnector.And
                    });
                }
            }

            var apiGateway = new ApiGateway(Token);
            var result = await apiGateway.Admin.GetPersone(request);
            return View("RiepilogoUtenti", result);
        }

        /// <summary>
        ///     Controller per visualizzare i dati dell' utente
        /// </summary>
        /// <param name="id">Guid utente</param>
        /// <returns></returns>
        [HttpGet]
        [Route("view/{id:guid}")]
        public async Task<ActionResult> ViewUtente(Guid id)
        {
            var currentUser = CurrentUser;
            var apiGateway = new ApiGateway(Token);
            var persona = await apiGateway.Admin.GetPersona(id);
            var ruoli = await apiGateway.Admin.GetRuoliAD();
            if (currentUser.IsGiunta)
            {
                ruoli.RemoveAt(ruoli.FindIndex(i => i.IDruolo == (int)RuoliIntEnum.Presidente_Regione));
                ruoli.RemoveAt(ruoli.FindIndex(i => i.IDruolo == (int)RuoliIntEnum.Assessore_Sottosegretario_Giunta));
            }
            var gruppiAD = await apiGateway.Admin.GetGruppiPoliticiAD();
            var listaGruppiRuoliAD = ruoli.Select(ruolo => new AD_ObjectModel
            {
                GruppoAD = ruolo.ADGroup,
                Membro = persona.Gruppi.Contains(ruolo.ADGroup.Replace(@"CONSIGLIO\", "")),
                IsRuolo = true
            }).ToList();
            listaGruppiRuoliAD.AddRange(gruppiAD.Select(gruppo => new AD_ObjectModel
            {
                GruppoAD = gruppo.GruppoAD,
                Membro = persona.Gruppi.Contains(gruppo.GruppoAD.Replace(@"CONSIGLIO\", "")),
                IsRuolo = false
            }));
            if (currentUser.IsGiunta)
            {
                var gruppo_giunta = gruppiAD.First(i => i.id_gruppo >= 10000);
                persona.id_gruppo_politico_rif = gruppo_giunta.id_gruppo;

                var gruppo_ad = listaGruppiRuoliAD.First(i => !i.IsRuolo);
                gruppo_ad.Membro = true;

                return View("ViewUtente", new ViewUtenteModel
                {
                    Persona = persona,
                    CurrentUser = currentUser,
                    GruppiAD = listaGruppiRuoliAD,
                    GruppiInDB = new List<KeyValueDto>
                    {
                        new KeyValueDto { id = gruppo_giunta.id_gruppo, descr = "GIUNTA" }
                    }
                });
            }

            var gruppiInDb = await apiGateway.Persone.GetGruppiAttivi();

            return View("ViewUtente", new ViewUtenteModel
            {
                Persona = persona,
                GruppiAD = listaGruppiRuoliAD,
                GruppiInDB = gruppiInDb.ToList(),
                CurrentUser = currentUser
            });
        }

        /// <summary>
        ///     Controller per creare un nuovo utente
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = RuoliExt.Amministratore_PEM + "," + RuoliExt.Amministratore_Giunta)]
        [HttpGet]
        [Route("new")]
        public async Task<ActionResult> NuovoUtente()
        {
            var currentUser = CurrentUser;
            var apiGateway = new ApiGateway(Token);
            var persona = new PersonaDto
            {
                userAD = @"CONSIGLIO\"
            };
            var ruoli = await apiGateway.Admin.GetRuoliAD();
            if (currentUser.IsAmministratoreGiunta)
            {
                ruoli.RemoveAt(ruoli.FindIndex(i => i.IDruolo == (int)RuoliIntEnum.Presidente_Regione));
                ruoli.RemoveAt(ruoli.FindIndex(i => i.IDruolo == (int)RuoliIntEnum.Assessore_Sottosegretario_Giunta));
            }
            var gruppiAD = await apiGateway.Admin.GetGruppiPoliticiAD();
            var listaGruppiRuoliAD = ruoli.Select(ruolo => new AD_ObjectModel
            {
                GruppoAD = ruolo.ADGroup,
                Membro = false,
                IsRuolo = true
            }).ToList();
            listaGruppiRuoliAD.AddRange(gruppiAD.Select(gruppo => new AD_ObjectModel
            {
                GruppoAD = gruppo.GruppoAD,
                Membro = false,
                IsRuolo = false
            }));
            if (currentUser.IsAmministratoreGiunta)
            {
                var gruppo_giunta = gruppiAD.First(i => i.id_gruppo >= 10000);
                persona.id_gruppo_politico_rif = gruppo_giunta.id_gruppo;

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/AdminPanel/RiepilogoSessioni.cshtml
@model System.Collections.Generic.List<PortaleRegione.DTO.Domain.SessioniDto>

@{
    ViewBag.Title = "Sessioni";
}

<script>
    $(document).ready(function() {
        $('#btnSearch').hide();
    });
</script>

<div class="row">
    <div class="col s12">
        <h4>
            <b>@ViewBag.Title</b>
        </h4>
    </div>
</div>

<div id="contentTable" class="row">
    <ul class="collection">
        @foreach (var sessione in Model)
        {
			<li class="collection-item">
                Utente: <b>@sessione.Persona.DisplayName</b>; Ingresso il: 
						<b>@sessione.DataIngresso.ToString("dd/MM/yyyy HH:mm")</b>; Uscita il: 
						<b>@((sessione.DataUscita.HasValue) ? sessione.DataUscita.Value.ToString("dd/MM/yyyy HH:mm") : "--")</b>;
                        Stato: <b>@sessione.Stato</b>; Chiusura corretta: <b>@(sessione.ChiusuraCorretta ? "Si": "No")</b>
			</li>
        }
    </ul>

    @if (!Model.Any())
    {
        <div class="row">
            <div class="col s12">
                <div class="card-panel panel-warning center">
                    <span class="center">
                        Non ci sono sessioni.
                    </span>
                </div>
            </div>
        </div>
    }
</div>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/AdminPanel/RiepilogoUtenti.cshtml
@using PortaleRegione.DTO.Enum
@using System.Linq
@using System.Web.Mvc.Html
@model PortaleRegione.DTO.Model.RiepilogoUtentiModel

@{
    ViewBag.Title = "Amministrazione";
}

@{
    foreach (var key in Context.Request.QueryString.AllKeys)
    {
        if (Equals(key, "q"))
        {
            break;
        }
    }
}

<div class="row">
    <div class="col s12">
        <h4>
            <b>@ViewBag.Title</b>
        </h4>
    </div>
</div>

@{
    Html.RenderPartial("_PaginationBar", Model.Data.Paging);
}

<div id="contentTable" class="row">

    @if (!Model.Data.Results.Any())
    {
        <div class="row">
            <div class="col s12">
                <div class="card-panel panel-warning center">
                    <span class="center">
                        Non ci sono persone. Controlla i filtri di ricerca.
                    </span>
                </div>
            </div>
        </div>
    }

    @foreach (var persona in Model.Data.Results)
    {
        var colorPin = "";
        var messaggio = "";
        switch (persona.Stato_Pin)
        {
            case StatoPinEnum.VALIDO:
            {
                messaggio = "Pin valido";
                colorPin = "green";
                break;
            }
            case StatoPinEnum.RESET:
            {
                messaggio = "Pin da resettare";
                colorPin = "orange";
                break;
            }
            case StatoPinEnum.NESSUNO:
            {
                messaggio = "Nessun pin impostato";
                colorPin = "red";
                break;
            }
        }
        <div class="col l6 m6 s12">
            <div class="card hoverable" title="@persona.DisplayName">
                <div class="card-action grey lighten-4 center">
                    <div class="row valign-wrapper" style="margin: 0 !important; padding: 0 !important">
                        <div class="col s6 left-align">
                            <div class="chip white-text @colorPin" style="min-width: unset">@messaggio</div>
                        </div>
                        <div class="col s6 right-align">
                            @if (Model.Persona.IsAmministratorePEM || Model.Persona.IsAmministratoreGiunta)
                            {
                                <button type="button" role="button" class="btn-flat black-text" onclick="openResetPin('@persona.UID_persona', '@persona.DisplayName')" title="RESET pin">
                                    <i class="material-icons">lock</i>
                                </button>
                                <button type="button" role="button" class="btn-flat black-text" onclick="openResetPassword('@persona.UID_persona', '@persona.DisplayName')" title="RESET password">
                                    <i class="material-icons">vpn_key</i>
                                </button>
                                <button type="button" role="button" class="btn-flat black-text" onclick="go('@Url.Action("ViewUtente", "AdminPanel", new { id = persona.UID_persona })')" title="Modifica @persona.UID_persona">
                                    <i class="material-icons">chevron_right</i>
                                </button>
                            }
                        </div>
                    </div>
                </div>
                <div class="card-content">
                    <div class="row valign-wrapper" style="margin: unset !important">
                        <div class="col s3 center">
                            <img class="responsive-img circle" style="height: 80px; width: 80px;" src='https://pubblicazioniweb.consiglio.regione.lombardia.it/fotocons/@persona.foto'>
                        </div>
                        <div class="col s9">
                            <h5 class="card-title truncate">
                                <span>@persona.DisplayName</span>
                            </h5>
                            <p>
                                @persona.userAD
                            </p>
                            <p>
                                @{
                                    var gruppi = "--";
                                    if (!string.IsNullOrEmpty(persona.Gruppi))
                                    {
                                        gruppi = persona.Gruppi;
                                    }
                                }
                                <b>Gruppi A.D. PEM:</b> @gruppi

                                @if (!string.IsNullOrEmpty(persona.GruppiAD))
                                {
                                    <i class="material-icons tiny activator">add</i>
                                }
                            </p>
                        </div>
                    </div>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">Altri Gruppi A.D.<i class="material-icons right">close</i></span>
                    <p>
                        @persona.GruppiAD
                    </p>
                </div>
            </div>
        </div>
    }
</div>

<input type="hidden" id="hdPersonaUID"/>
@{
    Html.RenderPartial("_RiepilogoUtentiFiltri", Model.Data);
    Html.RenderPartial("_RiepilogoUtenti_ModalResetPin");
    Html.RenderPartial("_RiepilogoUtenti_ModalResetPassword");
}

@if (Model.Persona.IsAmministratoreGiunta || Model.Persona.IsAmministratorePEM)
{
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large blue darken-3 tooltipped" data-position="bottom" data-tooltip="Nuovo utente"
           href="@Url.Action("NuovoUtente")">
            <i class="large material-icons">add</i>
        </a>
    </div>
}


@{
    Html.RenderPartial("_RiepilogoUtentiScript", Model.Data.Filters);
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/AdminPanel/ViewUtente.cshtml
@model PortaleRegione.Client.Models.ViewUtenteModel

@{
    var disable_fields = true;
    if (Model.Persona.UID_persona == Guid.Empty)
    {
        ViewBag.Title = "Nuovo utente";
        disable_fields = false;
    }
    else
    {
        ViewBag.Title = Model.Persona.DisplayName;
        disable_fields = Model.Persona.No_Cons == 0;
    }
    var backUrl = Url.Action("RiepilogoUtenti");
}

<script>
    $(document).ready(function() {
        $('#btnSearch').hide();
    });
</script>

<div class="row">
    <div class="col l1 s2">
        <button type="button" role="button" class="btn-floating grey darken-3 header-back" onclick="go('@backUrl')">
            <i class="material-icons">arrow_back</i>
        </button>
    </div>
    <div class="col l11 s10">
        <h4>
            <b>
                <span>@ViewBag.Title</span>
            </b>
        </h4>
    </div>
</div>
<div class="row">
    <div class="col s12">
        @using (Html.BeginForm("SalvaPersona", "AdminPanel", FormMethod.Post, new { id = "formPersona" }))
        {
            @Html.AntiForgeryToken()
            <input name="Persona.id_persona" type="hidden" value="@Model.Persona.id_persona" />

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.UID_persona)
                @Html.TextBoxFor(s => s.Persona.UID_persona, new
                {
                    @class = "form-control",
                    @readonly = true
                })
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.cognome)
                @if (disable_fields)
                {
                    @Html.TextBoxFor(s => s.Persona.cognome, new { @class = "form-control", @readonly = true })
                }
                else
                {
                    @Html.TextBoxFor(s => s.Persona.cognome, new { @class = "form-control" })
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.nome)
                @if (disable_fields)
                {
                    @Html.TextBoxFor(s => s.Persona.nome, new { @class = "form-control", @readonly = true })
                }
                else
                {
                    @Html.TextBoxFor(s => s.Persona.nome, new { @class = "form-control" })
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.email)
                @if (disable_fields)
                {
                    @Html.TextBoxFor(s => s.Persona.email, new { @class = "form-control", @readonly = true })
                }
                else
                {
                    @Html.TextBoxFor(s => s.Persona.email, new { @class = "form-control" })
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.foto)
                @if (disable_fields)
                {
                    @Html.TextBoxFor(s => s.Persona.foto, new { @class = "form-control", @readonly = true })
                }
                else
                {
                    @Html.TextBoxFor(s => s.Persona.foto, new
                    {
                        @class = "form-control"
                    })
                }
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.userAD)
                @Html.TextBoxFor(s => s.Persona.userAD, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(s => s.Persona.id_gruppo_politico_rif)
                <select id="ddlRiferimentoGruppo" @Html.Raw(Model.CurrentUser.IsGiunta ? "disabled=\"disabled\"" : "")>
                    <option value="0">--</option>
                    @foreach (var gruppo in Model.GruppiInDB)
                    {
                        if (Model.Persona.id_gruppo_politico_rif == gruppo.id)
                        {
                            <option value="@gruppo.id" selected="selected">@gruppo.descr</option>
                        }
                        else
                        {
                            <option value="@gruppo.id">@gruppo.descr</option>
                        }
                    }
                </select>
            </div>

            if (!Model.CurrentUser.IsGiunta)
            {
                <div class="form-group">
                    <p>
                        <label>
                            <input id="No_Cons" name="No_Cons" type="checkbox" value="true" disabled="disabled"
                                   @Html.Raw(Convert.ToBoolean(Model.Persona.No_Cons) ? "checked=\"checked\"" : "")>
                            <span>@Html.LabelFor(s => s.Persona.No_Cons)</span>
                        </label>
                    </p>
                </div>

                var notifica_Firma = Model.Persona.notifica_firma.HasValue ? Model.Persona.notifica_firma.Value : false;

                <div class="form-group">
                    <p>
                        <label>
                            <input id="notifica_firma" name="notifica_firma" type="checkbox" value="true"
                                   @Html.Raw(notifica_Firma ? "checked=\"checked\"" : "")>
                            <span>@Html.LabelFor(s => s.Persona.notifica_firma)</span>
                        </label>
                    </p>
                </div>

                var notifica_Deposito = Model.Persona.notifica_deposito.HasValue ? Model.Persona.notifica_deposito.Value : false;

                <div class="form-group">
                    <p>
                        <label>
                            <input id="notifica_deposito" name="notifica_deposito" type="checkbox" value="true"
                                   @Html.Raw(notifica_Deposito ? "checked=\"checked\"" : "")>
                            <span>@Html.LabelFor(s => s.Persona.notifica_deposito)</span>
                        </label>
                    </p>
                </div>

                var attivo = Model.Persona.attivo.HasValue ? Model.Persona.attivo.Value : false;

                <div class="form-group">
                    <p>
                        <label>
                            <input id="attivo" name="attivo" type="checkbox" value="true"
                                   @Html.Raw(attivo ? "checked=\"checked\"" : "")>
                            <span>@Html.LabelFor(s => s.Persona.attivo)</span>
                        </label>
                    </p>
                </div>

                var eliminato = Model.Persona.deleted.HasValue ? Model.Persona.deleted.Value : false;

                <div class="form-group">
                    <p>
                        <label>
                            <input id="deleted" name="deleted" type="checkbox" value="true" disabled="disabled"
                                   @Html.Raw(eliminato ? "checked=\"checked\"" : "")>
                            <span>@Html.LabelFor(s => s.Persona.deleted)</span>
                        </label>
                    </p>
                </div>
            }

            <div class="row">
                @foreach (var gruppiAD in Model.GruppiAD)
                {
                    var classCss = gruppiAD.IsRuolo ? "light-blue lighten-5" : "lime lighten-5";
                    <div class="col s3">
                        <div class="card @classCss">
                            <div class="card-content">
                                <p>
                                    <label>
                                        <input id="gruppiAD" name="gruppiAD" type="checkbox" value="true" data-name="@gruppiAD.GruppoAD"
                                               @Html.Raw(gruppiAD.Membro ? "checked=\"checked\"" : "") @Html.Raw(Model.CurrentUser.IsGiunta && !gruppiAD.IsRuolo ? "disabled=\"disabled\"" : "")>
                                        <span></span>
                                    </label>
                                </p>
                                <p class="truncate">@gruppiAD.GruppoAD</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
        @if (Model.Persona.UID_persona != Guid.Empty)
        {
            <div class="row">
                <div class="col s12">
                    @using (Html.BeginForm("EliminaPersona", "AdminPanel", FormMethod.Post, new { id = "formElimina" }
                        ))
                    {
                        @Html.AntiForgeryToken()
                        <a class="btn chip hoverable red center white-text" id="btnElimina" style="width: 255px;">
                            <i class="icon material-icons">close</i> Elimina
                        </a>
                    }
                </div>
            </div>
        }

        @if (Model.CurrentUser.IsAmministratoreGiunta || Model.CurrentUser.IsAmministratorePEM)
        {
            <div class="fixed-action-btn">
                <button id="btnSalvaUtente" class="btn-floating btn-large blue darken-3">
                    <i class="large material-icons">save</i>
                </button>
            </div>
        }
    </div>
</div>

<script>
    $("#btnSalvaUtente").on("click",
        function() {
            waiting(true);
            $('#formPersona').submit();
        });

    $("#formPersona").submit(function(e) {
        e.preventDefault();
    }).validate({
        submitHandler: function(form) {

            var groups = $('input[name="gruppiAD"]');

            var selected_groups = [];
            $.each(groups,
                function(index, item) {
                    selected_groups.push({
                        gruppoAd: $(item).data('name'),
                        membro: $(item).is(":checked")
                    });
                });
            var gruppo_riferimento = $("#ddlRiferimentoGruppo").children("option:selected");
            var id_gruppo_politico_rif = 0;
            $.each(gruppo_riferimento,
                function(index, item) {
                    id_gruppo_politico_rif = $(item).val();
                });
            var form_data = {
                uid_persona: $('input[name="Persona.UID_persona"]').val(),
                id_persona: $('input[name="Persona.id_persona"]').val(),
                nome: $('input[name="Persona.nome"]').val(),
                cognome: $('input[name="Persona.cognome"]').val(),
                email: $('input[name="Persona.email"]').val(),
                foto: $('input[name="Persona.foto"]').val(),
                userAd: $('input[name="Persona.userAD"]').val(),
                notifica_firma: $('input[name="notifica_firma"]').is(":checked"),
                notifica_deposito: $('input[name="notifica_deposito"]').is(":checked"),
                attivo: $('input[name="attivo"]').is(":checked"),
                deleted: $('input[name="deleted"]').is(":checked"),
                no_cons: $('input[name="No_Cons"]').is(":checked") ? 1 : 0,
                gruppiAd: selected_groups,
                id_gruppo_politico_rif: id_gruppo_politico_rif
            };

            //submit via ajax
            $.ajax({
                    url: '@Url.Action("SalvaPersona", "AdminPanel")',
                    type: "POST",
                    data: JSON.stringify(form_data),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json"
                }).done(function(dataResult) {
                    waiting(false);
                    if (dataResult.message)
                        swal({
                            title: "Errore",
                            text: dataResult.message,
                            icon: "error"
                        });
                    else {
                        if ($('input[name="Persona.UID_persona"]').val() == "@Html.Raw(Guid.Empty)") {
                            go(dataResult);
                        } else {
                            SuccessAlert("Profilo salvato correttamente");
                        }
                    }
                })
                .fail(function(err) {
                    console.log("error", err);
                    Error(err);
                });

            return false; //This doesn't prevent the form from submitting.
        }
    });

    $("#btnElimina").on("click",
        function() {
            waiting(true);
            $('#formElimina').submit();
        });

    $("#formElimina").submit(function(e) {
        e.preventDefault();
    }).validate({
        submitHandler: function(form) {
            
            //submit via ajax
            $.ajax({
                    url: '@Url.Action("EliminaPersona", "AdminPanel")' + "?id=@Html.Raw(Model.Persona.UID_persona)",
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json"
                }).done(function(dataResult) {
                    waiting(false);
                    if (dataResult.message)
                        swal({
                            title: "Errore",
                            text: dataResult.message,
                            icon: "error"
                        });
                    else {
                        if ($('input[name="Persona.UID_persona"]').val() == "@Html.Raw(Guid.Empty)") {
                            go(dataResult);
                        } else {
                            location.reload();
                        }
                    }
                })
                .fail(function(err) {
                    console.log("error", err);
                    Error(err);
                });

            return false; //This doesn't prevent the form from submitting.
        }
    });
</script>