Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/NotificheController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using PortaleRegione.Client.Helpers;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Model;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller notifiche
    /// </summary>
    [Authorize]
    [RoutePrefix("notifiche")]
    public class NotificheController : BaseController
    {
        [HttpGet]
        [Route("view")]
        public async Task<ActionResult> RiepilogoNotifiche(bool is_inviate, bool archivio, int page = 1, int size = 20)
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                RiepilogoNotificheModel model;
                if (!is_inviate)
                    model = await apiGateway.Notifiche.GetNotificheRicevute(page, size, archivio);
                else
                    model = await apiGateway.Notifiche.GetNotificheInviate(page, size, archivio);

                return View("RiepilogoNotifiche", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [HttpGet]
        [Route("counter-notifiche-ricevute")]
        public async Task<ActionResult> CounterRiepilogoNotifiche()
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                var res = await apiGateway.Notifiche.GetCounterNotificheRicevute();

                return Json(res, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [Route("{id}/destinatari")]
        public async Task<ActionResult> GetDestinatariNotifica(string id)
        {
            var apiGateway = new ApiGateway(Token);
            var destinatari = await apiGateway.Notifiche.GetDestinatariNotifica(id);
            var result = await Utility.GetDestinatariNotifica(destinatari, Token);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("destinatari")]
        public async Task<ActionResult> GetListaDestinatari(Guid atto, TipoDestinatarioNotificaEnum tipo)
        {
            var apiGateway = new ApiGateway(Token);
            var destinatari = await apiGateway.Notifiche.GetListaDestinatari(atto, tipo);
            return Json(destinatari, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("destinatari-dasi")]
        public async Task<ActionResult> GetListaDestinatari(TipoDestinatarioNotificaEnum tipo)
        {
            var apiGateway = new ApiGateway(Token);
            var destinatari = await apiGateway.Notifiche.GetListaDestinatari(tipo);
            return Json(destinatari, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("accetta-proposta")]
        public async Task<ActionResult> AccettaPropostaFirma(string id)
        {
            var apiGateway = new ApiGateway(Token);
            await apiGateway.Notifiche.AccettaPropostaFirma(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("accetta-ritiro")]
        public async Task<ActionResult> AccettaRitiroFirma(string id)
        {
            var apiGateway = new ApiGateway(Token);
            await apiGateway.Notifiche.AccettaRitiroFirma(id);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("archivia")]
        public async Task<ActionResult> ArchiviaNotifica(List<string> notifiche)
        {
            var apiGateway = new ApiGateway(Token);
            await apiGateway.Notifiche.ArchiviaNotifiche(notifiche);
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Notifiche/RiepilogoNotifiche.cshtml
@model PortaleRegione.DTO.Model.RiepilogoNotificheModel
@{
    ViewBag.Title = "Riepilogo notifiche";
}

<script>
    $(document).ready(function () {
        $('#btnSearch').hide();
    });
</script>

<div class="row" style="margin-bottom: unset !important">
    <div class="col s12">
        <button type="button" role="button" class="btn-floating waves-effect waves-light grey darken-3 header-back" href="javascript:history.go(-1)">
            <i class="material-icons">arrow_back</i>
        </button>
        <div class="row valign-wrapper">
            <div class="col s12">
                <h4>
                    <b>@ViewBag.Title</b>
                </h4>
            </div>
        </div>
    </div>
</div>
<hr/>

@{
    var inviateReq = HttpUtility.ParseQueryString(Request.Url.Query).Get("is_inviate");
    var is_inviate = false;
    if (!string.IsNullOrEmpty(inviateReq))
    {
        is_inviate = Convert.ToBoolean(inviateReq);
    }
}

<ul id="RiepilogoNotificheTabs" class="tabs tabs-fixed-width">
    <li class="tab col s3">
        <a class="@(!is_inviate ? "active" : "")" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = false, archivio = false})')">
            <i class="icon material-icons">move_to_inbox</i> Ricevute
        </a>
    </li>
    <li class="tab col s3">
        <a class="@(is_inviate ? "active" : "")" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = true, archivio = false})')">
            <i class="icon material-icons">send</i> Inviate
        </a>
    </li>
</ul>


@{
    Html.RenderPartial("_PaginationBar", Model.Data.Paging);
}

@if (!is_inviate)
{
    @Html.Partial("RiepilogoNotificheRicevute", Model)
}
else if (is_inviate)
{
    @Html.Partial("RiepilogoNotificheInviate", Model)
}

<script>

    function ArchiviaNotifica(ctrl, id_notifica){
        swal("Sei sicuro di voler archiviare la notifica?",
            {
                buttons: {
                    cancel: "Annulla",
                    confirm: {
                        className: "red white-text",
                        title: "Archivia",
                        value: true
                    }
                }
            }).then((value) => {
            if (value == true) {
                var url = '@Url.Action("ArchiviaNotifica", "Notifiche")';
                var notifiche = [];
                notifiche.push(id_notifica);
                $.ajax({
                    url: url,
                    type: "POST",
                    data: JSON.stringify(notifiche),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json"
                }).done(function(result) {

                    location.reload();

                }).fail(function(err) {
                    console.log("error", err);
                    Error(err);
                });
            }
        });
    }

    function RevealFirmaDeposito(id, action) {
	var text = "";
	var button = "";
	if (action == 3) {
		text = "Inserisci il PIN per firmare";
		button = "Firma";
	} else if (action == 4) {
		text = "Inserisci il PIN per presentare";
		button = "Presenta";
	}

	swal(text,
		{
			content: {
				element: "input",
				attributes: { placeholder: "******", className: "password" }
			},
			icon: "info",
			buttons: { cancel: "Annulla", confirm: button }
		})
		.then((value) => {
			if (value == null || value == "")
				return;

			waiting(true);
			$.ajax({
				url: baseUrl + "/emendamenti/azioni?id=" + id + "&azione=" + action + "&pin=" + value,
				method: "GET"
			}).done(function (data) {
				waiting(false);
				if (data.message) {
					var typeMessage = "error";
					var str = data.message;
					var pos = str.indexOf("OK");
					if (pos > 0) {
						typeMessage = "success";
					}
					swal({
						title: "Esito " + button,
						text: data.message,
						icon: typeMessage,
						button: "OK"
					}).then(() => {
						waiting(true);
                        location.reload();
						waiting(false);
					});
				} else {
					waiting(true);
					location.reload();
					waiting(false);
				}
			}).fail(function (err) {
				waiting(false);
				console.log("error", err);
				Error(err);
			});
		});
}

	function RevealFirmaDepositoDASI(id, action) {

		var text = "";
		var button = "";
		if (action == 3) {
			text = "Inserisci il PIN per firmare";
			button = "Firma";
		} else if (action == 4) {
			text = "Inserisci il PIN per presentare";
			button = "Presenta";
		}

		swal(text,
			{
				content: {
					element: "input",
					attributes: { placeholder: "******", className: "password" }
				},
				icon: "info",
				buttons: { cancel: "Annulla", confirm: button }
			})
			.then((value) => {
				if (value == null || value == "")
					return;

				waiting(true);
				$.ajax({
					url: baseUrl + "/dasi/azioni?id=" + id + "&azione=" + action + "&pin=" + value,
					method: "GET"
				}).done(function (data) {
					waiting(false);
					if (data.message) {
						var typeMessage = "error";
						var message = data.message;
						var str = data.message;
						var pos = str.indexOf("OK");
						if (pos > 0) {
							typeMessage = "success";
						}
						pos = str.indexOf("?!?");
						if (pos > 0) {
							typeMessage = "info";
							message = "Proposta di firma inviata al proponente";
						}

						swal({
							title: "Esito " + button,
							text: message,
							icon: typeMessage,
							button: "OK"
						}).then(() => {
							if (data.message.includes("OK") || data.message.includes("?!?")) {
								waiting(true);
								location.reload();
								waiting(false);
							}
						});
					}
				}).fail(function (err) {
					waiting(false);
					console.log("error", err);
					Error(err);
				});
			});
	}

</script>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Notifiche/RiepilogoNotificheInviate.cshtml
@using PortaleRegione.DTO.Model
@model PortaleRegione.DTO.Model.RiepilogoNotificheModel

@{
    var archivioReq = HttpUtility.ParseQueryString(Request.Url.Query).Get("archivio");
    var archivio = Convert.ToBoolean(archivioReq);
}
<div id="RiepilogoNotificheInviateTabs" class="row center-align">
    <div class="col s6">
        <button type="button" role="button" class="btn-flat @(!archivio ? "green-text" : "") chip" style="width: 100%" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = true, archivio = false})')">Attive</button>
    </div>
    <div class="col s6">
        <button type="button" role="button" class="btn-flat @(archivio ? "green-text" : "")" style="width: 100%" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = true, archivio = true})')">Archiviate</button>
    </div>
</div>

<div id="notificheInviateTable" class="row">
    @if (!Model.Data.Results.Any())
    {
        <div class="row">
            <div class="col s12">
                <div class="card-panel panel-warning center">
                    <span class="center">
                        Non ci sono notifiche inviate al momento
                    </span>
                </div>
            </div>
        </div>
    }
    else
    {
        <ul class="collapsible">
            @foreach (var notifica in Model.Data.Results)
            {
                <li>
                    @Html.Partial("_CardInvito", new CardInvitoModel
                    {
                        Data = notifica,
                        User = Model.CurrentUser,
                        Ricevute = false
                    })
                </li>
            }
        </ul>
    }
</div>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Notifiche/RiepilogoNotificheRicevute.cshtml
@using PortaleRegione.DTO.Model
@model PortaleRegione.DTO.Model.RiepilogoNotificheModel

@{
    var archivioReq = HttpUtility.ParseQueryString(Request.Url.Query).Get("archivio");
    var archivio = Convert.ToBoolean(archivioReq);
}
<div id="RiepilogoNotificheRicevuteTabs" class="row center-align">
    <div class="col s6">
        <button type="button" role="button" class="btn-flat @(!archivio ? "green-text" : "")" style="width: 100%" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = false, archivio = false})')">Attive</button>
    </div>
    <div class="col s6">
        <button type="button" role="button" class="btn-flat @(archivio ? "green-text" : "")" style="width: 100%" onclick="go('@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = false, archivio = true})')">Archiviate</button>
    </div>
</div>

<div id="notificheRicevuteTable" class="row">
    @if (!Model.Data.Results.Any())
    {
        <div class="row">
            <div class="col s12">
                <div class="card-panel panel-warning center">
                    <span class="center">
                        Non ci sono notifiche ricevute al momento
                    </span>
                </div>
            </div>
        </div>
    }
    else
    {
        <ul class="collapsible">
            @foreach (var notifica in Model.Data.Results)
            {
                <li>
                    @Html.Partial("_CardInvito", new CardInvitoModel
                    {
                        Data = notifica,
                        User = Model.CurrentUser,
                        Ricevute = true
                    })
                </li>
            }
        </ul>
    }
   
</div>