Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/PersoneController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using PortaleRegione.DTO.Model;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller persone
    /// </summary>
    [Authorize]
    [RoutePrefix("persone")]
    public class PersoneController : BaseController
    {
        [Route("{id:guid}")]
        public async Task<ActionResult> GetPersona(Guid id)
        {
            var apiGateway = new ApiGateway(Token);
            return Json(await apiGateway.Persone.Get(id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("all")]
        public async Task<ActionResult> GetPersone()
        {
            var apiGateway = new ApiGateway(Token);
            return Json(await apiGateway.Persone.Get(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("proponenti-firmatari")]
        public async Task<ActionResult> GetProponentiFirmatari(string legislaturaId)
        {
            var apiGateway = new ApiGateway(Token);
            return Json(await apiGateway.Persone.GetProponentiFirmatari(legislaturaId), JsonRequestBehavior.AllowGet);
        }

        [Route("cambio-pin")]
        public ActionResult CambioPin()
        {
            return View("CambioPinForm", new CambioPinModel());
        }

        [Route("check-cambio-pin")]
        [HttpPost]
        public async Task<ActionResult> CheckPin(CambioPinModel model)
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                await apiGateway.Persone.CheckPin(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [Route("conferma-cambio-pin")]
        [HttpPost]
        public async Task<ActionResult> SalvaPin(CambioPinModel model)
        {
            try
            {
                var apiGateway = new ApiGateway(Token);
                await apiGateway.Persone.SalvaPin(model);
                return Json("", JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(new ErrorResponse(e.Message), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [Route("gruppi-politici")]
        public async Task<ActionResult> GetGruppi()
        {
            var apiGateway = new ApiGateway(Token);
            return Json(await apiGateway.Persone.GetGruppiAttivi(), JsonRequestBehavior.AllowGet);
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Persone/CambioPinForm.cshtml
@model PortaleRegione.DTO.Model.CambioPinModel

@{
    ViewBag.Title = "Reimposta Pin";
}

<script>
    $(document).ready(function () {
        $('#btnSearch').hide();
    });
</script>

<div class="row">
    <div class="col l1 s2">
        <a class="btn-floating waves-effect waves-light grey darken-3 header-back" href="@Url.Action("RiepilogoSedute", "PEM")">
            <i class="material-icons">arrow_back</i>
        </a>
    </div>
    <div class="col l11 s10">
        <h5>
            <b>
                <span>@ViewBag.Title</span>
            </b>
        </h5>
    </div>
</div>

<div class="row">
    <div class="col s12">

        @using (Html.BeginForm("SalvaPin", "Persone", FormMethod.Post, new {id = "formCambioPin"}))
        {
            @Html.AntiForgeryToken()

            <div class="form-group" style="width: 100px">
                @Html.LabelFor(s => s.vecchio_pin)
                @Html.TextBoxFor(s => s.vecchio_pin, new {@class = "form-control", type = "password"})
            </div>
            <div class="form-group" style="width: 100px">
                @Html.LabelFor(s => s.nuovo_pin)
                @Html.TextBoxFor(s => s.nuovo_pin, new {@class = "form-control", type = "password"})
            </div>
            <div class="form-group" style="width: 100px">
                @Html.LabelFor(s => s.conferma_pin)
                @Html.TextBoxFor(s => s.conferma_pin, new {@class = "form-control", type = "password"})
            </div>

            <div class="fixed-action-btn">
                <button class="btn-floating btn-large blue darken-3" id="btnSave" type="button">
                    <i class="large material-icons">save</i>
                </button>
            </div>
        }
    </div>
</div>

<script>
    $("#btnSave").on("click",
        function () {
            setTimeout(function () {
                $('body').removeClass('loaded');
            }, 200);
            $('#formCambioPin').submit();
        });
    $("#formCambioPin").submit(function(e) {
        e.preventDefault();
    }).validate({
        submitHandler: function(form) {
            var body = JSON.parse(JSON.stringify($("#formCambioPin").serializeObject()));

            //submit via ajax
            $.ajax({
                url: baseUrl + "/persone/conferma-cambio-pin",
                type: "POST",
                data: JSON.stringify(body),
                contentType: "application/json; charset=utf-8",
                dataType: "json"
            }).done(function(data) {
                if (data.message)
                    swal({
                        title: "Errore",
                        text: data.message,
                        icon: "error"
                    });
                else {
                    SuccessAlert("Il pin è stato correttamente cambiato!");
                    go(data)
                }
                
            }).fail(function(err) {
                console.log("error", err);
                Error(err);
            });

            return false; //This doesn't prevent the form from submitting.
        }
    });
</script>